### ISSUE TITLE
Add loopback feature regression tests

### ISSUE THREAD

**Issue by digitalsadhu** [digitalsadhu/loopback-component-jsonapi#27] opened 2015-10-15 17:43 UTC
Theres a risk that as we modify the way loopback accepts and returns data to match the JSON API spec, we may break things that we aren't aware of. It would be great if someone could find the time to add some basic tests to cover various features:

It should be pretty straight forward to create the tests, just refer to the tests we have all ready in the test folder.

Some areas that could use testing are:
- referencesMany relationships
- embedsOne, embedsMany etc
- the built in user model methods like login and logout
- etc

**Comment by taras** [comment] 2015-12-26 04:47
I might have found such a regression in `the built in user model methods like login` use case. When a user is registering, the response needs to include the accessToken#id. This is not happening, because the accessToken record is not side loaded. It might be addressed by #38 but it's not obvious if that PR covers the POST method.

**Comment by digitalsadhu** [comment] 2015-12-26 08:20
Hey and thanks for reporting!
I doubt #38 will address any issues with login I'm afraid. 

I think we need to do a better job of where and when we apply jsonapi to built in methods. 

I don't suppose you'd be up for having a go at adding a test or 2 that illustrates the issue you are seeing?

**Comment by taras** [comment] 2015-12-26 11:34
@digitalsadhu created PR #82 

We should still apply JSONAPI to this method but we could manually sideload that data. 

What do you think?

**Closed** 2017-06-10 06:46 UTC
Labels: help wanted
