### ISSUE TITLE
Add application/vnd.api+json to explorer

### ISSUE THREAD

**Issue by tsteuwer** [digitalsadhu/loopback-component-jsonapi#29] opened 2015-10-18 21:59 UTC
While working on #15 I noticed we have no way to test the explorer with the json api. We need the drop down to include this.

**Comment by digitalsadhu** [comment] 2015-10-24 07:51
This is a duplicate of #3 Theres some info there about why its a little tricky to do this. It's going to require a change to the loopback framework itself to allow this. I'll look into submitting a patch myself with guidance from @bajtos hopefully

**Comment by digitalsadhu** [comment] 2015-10-24 07:54
Closing for now, continue any discussion on #3

**Closed by digitalsadhu** 2015-10-24 07:54 UTC
